### ISSUE TITLE
Fatal error when deleting mail account

### ISSUE THREAD

**Issue by kbnKS** [rubenarslan/formr.org#287]
I get a "fatal error" message when I try to delete an old mail account, that we only created for test purposes and don't need anymore. This is the date and time of the error message of the first or second attempt: 2017-04-20 09:03:05

**Comment by rubenarslan** [comment]
This happens if the email account has been used to send emails already. Because there would be a inconsistency in our database for sent emails. We'll figure out how to handle this more reasonably (i.e. make it so that it's still clear where old emails were sent from) and in the meanwhile will try to display an informative error message.
