### ISSUE TITLE
improve monkey mode for text [0-9], mc, block, & month

### ISSUE THREAD

**Issue by selinakreinhard** [rubenarslan/formr.org#321]
Monkey mode does not work for these items:
- text [0-9]: 
Item is filled out like a normal text item "thank the formr monkey" instead of a number
- mc [answer defined in choices] followed by conditional text item: 
2 clicks are needed. After the first one, mc is filled out and a second click is needed so the monkey also fills out the following text item
- block item:
If easy to implement, it would be nice if the monkey would fill out items so progress is not blocked. Alternatively, let user decide whether block items should be activated while testing with the formr monkey.
- month 01.01.1920,now:
monkey does not give a valid answer

**Comment by rubenarslan** [comment]
I think this is outside our scope. The monkey is stupid and so it doesn't understand any requirements. Making it understand some would not be that much work, but all possible requirements? If somebody has invested effort into producing a smarter "monkey" tool elsewhere, we can use it, but I didn't find anything the last time I searched.
I don't like the idea of allowing to ignore requirements like the block items, because you will generate invalid and (for normal users) impossible data for your tests.
