### ISSUE TITLE
Pause with time set to 0 gets users stuck

### ISSUE THREAD

**Issue by kthorstmann** [rubenarslan/formr.org#457]
When setting a time in the pause module to 0, participants get stuck in the pause module. The correct behavior would be if they were immediately sent to the next module. 

Additionally Ruben asked me to add that it would be useful if pauses could also handle fractions (e.g., seconds). Thanks!

**Comment by cyriltata** [comment]
@kthorstmann I started looking at issues here so coming back to you on this. Please could you provide an example of which you got stuck? 
I tried to replicate the issue by using a pause unit with "wait this many minutes = 0" and moved on immediately.

Also setting the wait time to seconds might lead to many complaints because the "queue" running behind the scenes needs time of its own to process the session. In reality the time defined in the pause is always off by a couple of seconds. Using seconds here might just be more confusing.

**Comment by kthorstmann** [comment]
Hi Cyril, sorry, I think by now I am unable to replicate this problem, we have however not had this issue any more as we have re-activated this pause.
