### ISSUE TITLE
warning message in waiting time when "relative to" contains a comment 

### ISSUE THREAD

**Issue by kthorstmann** [rubenarslan/formr.org#473]
I added text as a comment in a waiting time (see picture; sometimes to describe what the waiting time does, <img width="661" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/13737750/127474626-794d276f-a843-4069-b11f-a7d82a04e886.png">
). This led to (a) a warning message and (b) the test user did not skip over the waiting time, only after reloading the page (see <img width="1159" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/13737750/127474583-48ee40c3-a82e-4eb5-83b4-6d741a9863b7.png">). Maybe comments could be excluded from the evaluation.

**Comment by rubenarslan** [comment]
Hi Kai, that is intended new behavior. We are trying to be a bit clearer about the intended consequences of user written code, so that it becomes easier to identify why things go wrong. I hope the error message helped you diagnose why your old approach broke. Just put the comment in the description (next to the number of the module).
