### ISSUE TITLE
Error: parse error: premature EOF (right here) ------^

### ISSUE THREAD

**Issue by TarJae** [rubenarslan/formr.org#526]
Update (relevant information):
1. Meanwhile, I can access my formr account and create a survey from R, which indicates that the connection is correct.
2. More importantly, when I manually download the .json file, it has a size of 0 KB even though I can see the results. Moreover, downloading the results as .xlsx or .csv files displays all the results correctly."

There must be an issue in the creation of the json file, but I can't find out where. All of the surveys (2 done by me and 1 from the net) show the same behavior. 

First post: 
Thank you immensely for your patience. I noticed a note in the documentation within the example section that reads as follows:
```
## Not run: 
formr_raw_results(survey_name = 'training_diary' )

## End(Not run)
```
This explains why I was confused about the host. However, the clarification was actually provided in the preceding lines. My apologies for the oversight.

Now, when I attempt the following:
```
formr::formr_raw_results(survey_name = 'my_study', host = "https://workshops.formr.org")
```
I encounter this error:
```
Error: parse error: premature EOF
                                       
                     (right here) ------^
```
I greatly appreciate your patience and assistance!

_Originally posted by @TarJae in https://github.com/rubenarslan/formr.org/issues/525#issuecomment-1962996730_

**Comment by rubenarslan** [comment]
No need to open a new issue if your problem is not solved. I'm tagging @cyriltata who may know what's up.

**Comment by igorduartt** [comment]
Hey, same problem here. I'll be following more news on this issue. Thank you!

**Comment by rubenarslan** [comment]
hi @igorduartt I'll need to know a bit more. which instance of formr are you using (what URL), what code are you running in R, etc.

**Comment by cyriltata** [comment]
@igorduartt, please can you ping me privately with your email address and I
grant you API access so that you could try that?  Without seeing the actual
response from the server it will  be hard to say what is going on.

**Comment by igorduartt** [comment]
Hi @rubenarslan! I'm using the host https://workshops.formr.org/. I did a lot of research here on the forum and saw some suggestions and I'm using this code block for the connection

`formr::formr_connect(email = "@", password = "***", 
                     host = "https://workshops.formr.org/")`

`df <- formr::formr_raw_results(survey_name = "NAPESE_PCL5_", 
                                   host = "https://workshops.formr.org/")`

I did the same as my colleague, I tried to download the json from my bank and it came up blank. I don't know if that's enough, please, if you need more information, just let me know!

**Comment by rubenarslan** [comment]
So, if you manually try to download your study data as JSON, you get an error/blank file even though you have data? Then, I think the problem is not with the automated export @cyriltata but probably with the module we used for JSON, xsendfile. Cyril, can you check you have
`a2enmod rewrite headers ssl xsendfile proxy proxy_http proxy_balancer`

**Comment by cyriltata** [comment]
@ChristianW-Goe Are you also trying to download results in JSON? Or over the API?

**Comment by ChristianW-Goe** [comment]
> [@ChristianW-Goe](https://github.com/ChristianW-Goe) Are you also trying to download results in JSON? Or over the API?

In R-Studio, using
```
formr::formr_connect(email_GEMI, password_GEMI, host="https://formr.psych.uni-goettingen.de")
formr::formr_raw_results(survey_name="pre", host="https://formr.psych.uni-goettingen.de")
```

**Comment by ChristianW-Goe** [comment]
I could not replicate the issue on the public instance of formr (formr.org).

On both instances, when a survey is entirely empty (0 test cases, 0 live cases), I get:

```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html>     <hea
                     (right here) ------^
```

Once the dataset contains at least one case (test or live), the content of our survey ("pre" and alle others) produces different outcomes on the two instances. 

On the public instance, everything works well ✅, whereas on the GEMI instance (https://formr.psych.uni-goettingen.de), I get ⚠️

```
Error: parse error: premature EOF
                                       
                     (right here) ------^
```

For our project, this issue doesn't matter anymore because we moved our study back to the public instance and started data collection now. 😌

As this issue is already marked as "closed", I'll tag both of you once again in case that this message contains some information that might be relevant for you. 

Once again, thank you so much for developing and refining this awesome software, @rubenarslan and @cyriltata ! 🥹

We are amazed by its logical structure and that it provides access to the huge capabilities of R combined with beautiful responsive design and user interface!
